### ISSUE TITLE
主题布局错乱

### ISSUE THREAD

**Issue by huasio** [yannisme/flarum-cn-theme#1]
主页的布局和内容的页的布局有点错乱。

![image](https://user-images.githubusercontent.com/23445537/137422856-56c800dc-7514-4f4e-bc94-9bd23198e204.png)
![image](https://user-images.githubusercontent.com/23445537/137422926-2aa7857c-ae04-4aae-b640-b929aca0928e.png)

**Comment by yannisme** [comment]
已修复，第二个问题属于投票扩展中元素未定义class或者id，所以没办法进行调整。
https://github.com/yannisme/flarum-cn-theme/commit/2ae58195907f44bb50389ad7cb39851717f70de3
