### ISSUE TITLE
嵌入视频或插入表格时，点赞/回复区块与表格/视频区块重叠

### ISSUE THREAD

**Issue by 1kuxyz** [yannisme/flarum-cn-theme#2]
![image](https://user-images.githubusercontent.com/40167317/147178536-23275a1c-e218-4dae-b3e0-bfac2ad18785.png)

**Comment by yannisme** [comment]
试试看，位置可以自己调整一下，这个重叠的问题后续会想办法修复的
.Post-actions {
    bottom: -35px!important
}

**Comment by yannisme** [comment]
在平板端以上分辨率，将会显示在侧边，避免这个遮挡的问题。
https://github.com/yannisme/flarum-cn-theme/commit/53cecb1f512b5f37
![image](https://user-images.githubusercontent.com/20273789/147402413-b887ef4d-404b-4deb-bc56-d7d5c0e32515.png)
